on:
  push:
    branches:
      - master
  pull_request:
    types: [ opened, reopened, synchronize ]

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
        matrix:
            node: [14, 16]
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node }}
      - uses: c-hive/gha-yarn-cache@v1
      - name: Install deps
        run: yarn install
      - name: Bootstrap repo
        run: yarn bootstrap
      - name: Build packages
        run: yarn build
      - name: Lint tools
        run: yarn lint
      - name: Run tests
        env:
            NODE_OPTIONS: --max_old_space_size=4096
        run: yarn testAll
      - name: Coveralls
        uses: coverallsapp/github-action@master
        if: matrix.node == '12'
        with:
            github-token: ${{ secrets.GITHUB_TOKEN }}
